name: runnable old node
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: example

jobs:
  runnable:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 6, 7, 8, 9, 10.x, 11.x, 12.x, 13.x ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install leo-profanity

      - name: Run with CommonJS
        run: node commonjs.js
